name: Deploy Ghost Theme

on:
  workflow_dispatch:        # ← enables the “Run workflow” button
  push:
    branches: [ main, master ]
    paths:
      - 'edition-clean/**'
      - '.github/workflows/deploy-theme.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # in your GitHub Action before build
      - name: Validate package.json parses
        run: node -e "JSON.parse(require('fs').readFileSync('edition-clean/package.json','utf8'))"

      # Debug: list files so we can see the theme folder in logs
      - name: Show repo structure (debug)
        run: |
          pwd
          ls -la
          ls -la edition-clean || true
          test -f edition-clean/package.json && echo "package.json found" || echo "package.json MISSING"

      # Validate theme before deploy (prints human-readable errors if any)
      - name: Validate theme with gscan (prints real errors)
        run: |
          npx -y gscan@latest --fatal --verbose edition-clean

      # Create a zip of the theme folder
      - name: Build theme zip
        run: |
          cd edition-clean
          zip -r ../theme.zip . -x "node_modules/*" "**/.DS_Store" "**/__MACOSX/*"
          cd ..

      # Upload the zip to Ghost
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: theme.zip
